CREATE DATABASE youtube;


CREATE TABLE users (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 firstname VARCHAR(100) NOT NULL,
 lastname VARCHAR(100) NOT NULL,
 email VARCHAR (120) NOT NULL UNIQUE,
 password VARCHAR(50) NOT NULL ,
 created_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
 );
 
CREATE TABLE channels (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 name_channel VARCHAR(50) UNIQUE,
 video_id INT UNIQUE,
 playlist_id INT ,
 created_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
);

CREATE TABLE videos (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 video_name VARCHAR(50) NOT NULL,
 video_file LONGBLOB NOT NULL ,
 genre_type_id INT UNSIGNED,
 created_at DATETIME DEFAULT NOW()
);

CREATE TABLE genre_types (
 genre_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 genre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE news (
 user_id INT UNSIGNED NOT NULL,
 body TEXT,
 created_at DATETIME DEFAULT NOW()
);

CREATE TABLE subscribers (
 channel_id INT UNSIGNED NOT NULL,
 subscriber_id INT UNSIGNED NOT NULL,
 requested_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
 PRIMARY KEY (channel_id,subscriber_id)
);


CREATE TABLE views (
 user_id INT UNSIGNED NOT NULL,
 video_id INT UNSIGNED NOT NULL,
 created_at DATETIME DEFAULT NOW()
);

CREATE TABLE comments (
 user_id INT UNSIGNED NOT NULL,
 video_id INT UNSIGNED NOT NULL,
 body TEXT NOT NULL,
 created_at DATETIME DEFAULT NOW(),
 PRIMARY KEY (user_id,created_at)
);


CREATE TABLE likes (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 item_id INT UNSIGNED NOT NULL,
 like_type_id INT UNSIGNED NOT NULL,
 user_id INT UNSIGNED NOT NULL,
 created_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP 
 );
 
 CREATE TABLE dislikes (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 item_id INT UNSIGNED NOT NULL,
 dislike_type_id INT UNSIGNED NOT NULL,
 user_id INT UNSIGNED NOT NULL ,
 created_at DATETIME DEFAULT NOW(),
 updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
);


CREATE TABLE like_types (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
 name VARCHAR(255) NOT NULL UNIQUE
 );
 
CREATE TABLE playlists (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
 user_id INT UNSIGNED NOT NULL,
 name VARCHAR(50) ,
 video_id INT UNSIGNED NOT NULL 
);




 
 